10 '$EXTERN Cadd(INTEGER, INTEGER) AS INTEGER
20 '$EXTERN Chypot(DOUBLE, DOUBLE) AS DOUBLE
30 '$EXTERN Greet(STRING) AS STRING
40 '$EXTERN Getn AS INTEGER
50 '$EXTERN Upcase(STRING) AS STRING
60 PRINT "sum="; Cadd(3, 4)
70 PRINT "hyp="; Chypot(3, 4)
80 A$ = "World"
90 PRINT Greet(A$)
100 PRINT Greet("BASIC")
110 PRINT "getn="; Getn
120 PRINT Upcase("hello")
130 END
